spring:
  application:
    name: bgll_hospital
  profiles:
    active: dev
  datasource:
    driver-class-name: ${mysql.driver-class-name}
    url: ${mysql.url}
    username: ${mysql.username}
    password: ${mysql.password}
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password}
  rabbitmq:
    password: ${rabbitmq.password}
    username: ${rabbitmq.username}
    host: ${rabbitmq.host}
    port: ${rabbitmq.port}
  ai:
    openai:
      api-key: ${openai.api-key}
      base-url: ${openai.base-url}
      chat:
        options:
          model: ${openai.chat.model}
          temperature: ${openai.chat.temperature}
      embedding:
        options:
          model: ${openai.embedding.model}
          dimensions: ${openai.embedding.dimensions}
server:
  address: 0.0.0.0
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cug.domain.pojo
  configuration:
    map-underscore-to-camel-case: true

bgll:
  sms:
    host: ${sms.host}
    path: ${sms.path}
    templateId: ${sms.templateId}
    appcode: ${sms.appcode}

  jwt:
    user:
      name: ${jwt.user.name}
      secret: ${jwt.user.secret}
      expiration: ${jwt.user.expiration}
    doctor:
      name: ${jwt.doctor.name}
      secret: ${jwt.doctor.secret}
      expiration: ${jwt.doctor.expiration}